config/routes.rb
ContactManager::Application.routes.draw do
  resources :contacts

  root 'contacts#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  # todo: Add more validation for proper states later
  validates_presence_of :street, :city, :postcode, :state
  belongs_to :contact
end

app/models/contact.rb
require 'digest/md5'
class Contact < ActiveRecord::Base
  validates_uniqueness_of :name
  validates_presence_of :name, :sex, :age, :birthday, :phone, :email
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :age, inclusion: { in: 1..150 }
  validates :sex, inclusion: { in: %w{male female} }

  validates :avatar_url, :format => URI::regexp(%w(http https))
  has_many :addresses

  def avatar(size = 20)
    md5 = Digest::MD5.hexdigest(email).to_s
    avatar_url.present? ? avatar_url : "http://www.gravatar.com/avatar/#{md5}.jpg?s=#{size}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
# require './app/service_interfaces/contact_si'
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = ContactSI.new do |c|
      c.set_contact = contact_params
      c.set_addresses = address_params
    end.save


    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :sex, :age, :birthday, :phone, :email, :avatar_url)
  end

  def address_params
    params.require(:address).permit(:street, :city, :state, :postcode)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.haml
= form_for @contact, role: 'form' do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-12
      .form-group
        = f.text_field :name, class: 'form-control input-lg', placeholder: 'Full Name'
  %hr
  .row
    .col-md-3
      %center
        - if @contact.try(:email)
          %img{src: "#{@contact.avatar(150)}", style: "width: 120px;"}
        - else
          %img{src: "http://placehold.it/150x150"}
    .col-md-9

      .row
        .col-md-4
          .form-group
            = f.label :sex
            %br
            = f.select :sex, options_for_select(['male', 'female']), class: 'form-control'

        .col-md-4
          .form-group
            = f.label :age
            = f.text_field :age, class: 'form-control'
        .col-md-4
          .form-group
            = f.label :birthday
            %br
            = f.date_select :birthday, class: 'form-control'
      - fa = @contact.addresses.first
      = fields_for :address do |a|
        .row
          .col-md-12
            .form-group
              = a.label :street
              = a.text_field :street, value: fa.try(:street), class: 'form-control'
        .row
          .col-md-4
            .form-group
              = a.label :city
              = a.text_field :city, value: fa.try(:city), class: 'form-control'
          .col-md-4
            .form-group
              = a.label :state
              = a.text_field :state, value: fa.try(:state), class: 'form-control'
          .col-md-4
            .form-group
              = a.label :postcode
              = a.text_field :postcode, value: fa.try(:postcode), class: 'form-control'


      .row
        .col-md-4
          .form-group
            = f.label :phone
            = f.text_field :phone, class: 'form-control'
        .col-md-4
          .form-group
            = f.label :email
            = f.text_field :email, class: 'form-control'
        .col-md-4
          .form-group
            = f.label :avatar_url
            = f.text_field :avatar_url, class: 'form-control'

      .row
        .col-md-6
          .actions
            = f.submit 'Save Contact', class: 'btn btn-success col-md-12'

app/views/contacts/edit.html.haml
%h1 Editing

= render 'form'

app/views/contacts/index.html.haml
%h1 All Contacts

%table.table
  %tr
    %th Name
    %th Sex
    %th Age
    %th Birthday
    %th Phone
    %th Email
    %th
    %th
    %th

  - @contacts.each do |contact|
    %tr
      %td= contact.name
      %td= contact.sex
      %td= contact.age
      %td= contact.birthday
      %td= contact.phone
      %td= contact.email
      %td= link_to 'Show', contact
      %td= link_to 'Edit', edit_contact_path(contact)
      %td= link_to 'Destroy', contact, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/contacts/new.html.haml
= render 'form'

app/views/contacts/show.html.haml
.row
  .col-md-12
    .form-group
      %h2
        =@contact.name
        %a{href: "#{edit_contact_path(@contact)}"}
          %i.glyphicon.glyphicon-pencil
%hr
.row
  .col-md-3
    %center
      %img{src: "#{@contact.avatar(150)}", style: "width: 120px;"}
  .col-md-9

    .row
      .col-md-4
        .form-group
          = label_tag :sex
          %br
          = @contact.sex

      .col-md-4
        .form-group
          = label_tag :age
          %br
          = @contact.age
      .col-md-4
        .form-group
          = label_tag :birthday
          %br
          = @contact.birthday
    - @contact.addresses.each do |address|
      .row
        .col-md-12
          .form-group
            = label_tag :street
            %br
            = address.street
      .row
        .col-md-4
          .form-group
            = label_tag :city
            %br
            = address.city
        .col-md-4
          .form-group
            = label_tag :state
            %br
            = address.state
        .col-md-4
          .form-group
            = label_tag :postcode
            %br
            = address.postcode


    .row
      .col-md-6
        .form-group
          = label_tag :phone
          %br
          = @contact.phone
      .col-md-6
        .form-group
          = label_tag :email
          %br
          = @contact.email

app/views/layouts/application.html.haml
!!!
%html{lang: "en", xmlns: "http://www.w3.org/1999/xhtml", "xmlns:fb" => "http://www.facebook.com/2008/fbml"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    = csrf_meta_tags
    = javascript_include_tag :application
  %body
    / Latest compiled and minified CSS
    %link{href: "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", rel: "stylesheet"}/
    / Optional theme
    %link{href: "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css", rel: "stylesheet"}/
    / Latest compiled and minified JavaScript
    %script{src: "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"}

    / Header
    #top-nav.navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.icon-toggle
          %a.navbar-brand{href: "/"} Contact Manager
    / /Header
    / Main
    .container
      .row
        .col-md-3
          / Left column
          %a{href: "#{new_contact_path}"}
            %strong.btn.btn-success.col-md-12
              %i.glyphicon.glyphicon-plus-sign
              New Contact
          %hr/
          %hr/
          %ul.nav.nav-pills.nav-stacked
            %li.nav-header
            - Contact.all.each do |contact|
              %li
                %a{href: "#{contact_path(contact)}"}
                %img{src: "#{contact.avatar}", style: "width: 20px"}
                  = contact.name

        / /col-3
        .col-md-9
          .row
            / center left
            .col-md-12
              = yield
    / /Main
    %footer.text-center
    #addWidgetModal.modal
      .modal-dialog
        .modal-content
          .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
            %h4.modal-title Add Widget
          .modal-body
            %p Add a widget stuff here..
          .modal-footer
            %a.btn{"data-dismiss" => "modal", href: "#"} Close
            %a.btn.btn-primary{href: "#"} Save changes
        / /.modal-content
      / /.modal-dalog
    / /.modal